Support PHP Redis 5.2.1
snc/SncRedisBundle pull request #587
Opened 2020-08-17 16:46 UTC by nesk

A simple commit to fix the declaration of `zAdd()` for phpredis 5.2.1. This commit is backward compatible with older versions of phpredis since it only adds an argument to the function: https://github.com/phpredis/phpredis/commit/977c4213c190bb1fc43782d757d8d386eb42015e

Fixes #583

2020-08-24 13:19 UTC, curry684 commented
Is changing the signature to variadic in overrides supported in our lowest supported PHP versions?

2020-08-24 16:58 UTC, nesk commented
Variadic-length argument lists are supported since PHP 5.6: https://www.php.net/manual/en/functions.arguments.php#functions.variable-arg-list

This package supports PHP >= 7.1.3.

2020-08-25 07:34 UTC, curry684 commented
I know, the question is whether it triggers errors in PHP to override the function with different arguments (overloading is not supported).

2020-08-31 10:50 UTC, nesk commented
Honestly, I'm not sure I understand the question. 😕

The behaviour before this commit is the one described in #583, the behaviour after this commit is making the warning disappear in all the supported PHP versions.

If this is not enough, I would be glad to provide more informations but currently I don't really understand what you're asking for. 😅

2020-09-07 10:22 UTC, divine commented
> I know, the question is whether it triggers errors in PHP to override the function with different arguments (overloading is not supported).

Any update? Did you find a way to check the function with different arguments?

2020-09-07 10:51 UTC, divine requested changes
Could you please take a look at https://github.com/snc/SncRedisBundle/blob/master/Client/Phpredis/ClientCluster.php#L992 ?

Thanks!

2020-09-10 04:20 UTC, yellow1912 commented
This one should be merged ASAP. It does fixes current issue and does not introduce any backward incompatibility.

2020-09-10 11:08 UTC, yellow1912 commented
@nesk I think what @curry684 meant is that if you run this code on OLD phpredis then does it work or not? Now that I think about it, it may not work.

2020-09-15 16:35 UTC, nesk commented
I've just tried to use 5.2.0 with my fix, I don't see any issues:

```
$ echo '\n' | pecl install -f redis-5.2.0
[Some logs...]

$ php -i | grep 'Redis Version'
Redis Version => 5.2.0

$ php -r 'require "vendor/autoload.php"; new Snc\RedisBundle\Client\Phpredis\Client;'
[Not output, exit code = 0]

$ echo '\n' | pecl install -f redis
[Some logs...]

$ php -i | grep 'Redis Version'
Redis Version => 5.3.1

$ php -r 'require "vendor/autoload.php"; new Snc\RedisBundle\Client\Phpredis\Client;'
[Not output, exit code = 0]
```

FYI, here's the output the PHP script if I remove my fix:

```
$ php -r 'require "vendor/autoload.php"; new Snc\RedisBundle\Client\Phpredis\Client;'
PHP Warning:  Declaration of Snc\RedisBundle\Client\Phpredis\Client::zAdd($key, $score1, $value1, $score2 = NULL, $value2 = NULL, $scoreN = NULL, $valueN = NULL) should be compatible with Redis::zAdd($key, $score, $value, ...$extra_args) in /Users/johann/Development/SncRedisBundle/Client/Phpredis/Client.php on line 1077

Warning: Declaration of Snc\RedisBundle\Client\Phpredis\Client::zAdd($key, $score1, $value1, $score2 = NULL, $value2 = NULL, $scoreN = NULL, $valueN = NULL) should be compatible with Redis::zAdd($key, $score, $value, ...$extra_args) in /Users/johann/Development/SncRedisBundle/Client/Phpredis/Client.php on line 1077
```

2020-09-19 23:55 UTC, divine commented
After one month still this isn't fixed.

No maintainers @snc?

2020-10-08 09:27 UTC, Miloud-H commented
Hi, any news for this PR ?

2020-10-16 13:57 UTC, merged

2020-10-16 13:58 UTC, B-Galati commented
Thanks @nesk and sorry for the delay. Please let me know how it goes and if a revert is needed. I'll do the release asap.

2020-10-16 14:09 UTC, nesk commented
No worries, thank you for the merge. 🙂

2020-10-16 18:04 UTC, divine commented
> No worries, thank you for the merge. 🙂

No fix for ClientCluster.php?



> Could you please take a look at https://github.com/snc/SncRedisBundle/blob/master/Client/Phpredis/ClientCluster.php#L992 ?
> 
> Thanks!

?

2020-11-06 19:17 UTC, B-Galati commented
See https://github.com/snc/SncRedisBundle/pull/596 @divine